services:
  db2:
    image: icr.io/db2_community/db2:11.5.8.0
    container_name: db2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=passw0rd
      - DBNAME=PHOTODB
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - UPDATEAVAIL=NO
      - TO_CREATE_SAMPLEDB=false
      - REPODB=false
      - IS_OSXFS=false
      - PERSISTENT_HOME=true
      - HADR_ENABLED=false
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/database
    restart: unless-stopped
    shm_size: 1g
    healthcheck:
      test: ["CMD", "su", "-", "db2inst1", "-c", "db2 connect to PHOTODB && db2 quit"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      db2:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=db2
      - DB_URL=jdbc:db2://db2:50000/PHOTODB
      - DB_USER=db2inst1
      - DB_PASS=passw0rd
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      # Flyway configuration - temporarily enabled for schema migration
      - FLYWAY_ENABLED=true
      - FLYWAY_LOCATIONS=classpath:db/migration
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_VALIDATE_ON_MIGRATE=true
      - FLYWAY_CLEAN_DISABLED=true
      - FLYWAY_REPAIR_ON_MIGRATE=true
      # JPA configuration
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - JPA_FORMAT_SQL=false
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080/api
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db2_data:
    driver: local


