services:
  db2:
    image: icr.io/db2_community/db2:11.5.8.0
    container_name: db2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=passw0rd
      - DBNAME=PHOTODB
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - UPDATEAVAIL=NO
      - TO_CREATE_SAMPLEDB=false
      - REPODB=false
      - IS_OSXFS=false
      - PERSISTENT_HOME=true
      - HADR_ENABLED=false
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/database
    restart: unless-stopped
    shm_size: 4g

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db2
    environment:
      - SPRING_PROFILES_ACTIVE=db2
      - DB_URL=jdbc:db2://db2:50000/PHOTODB
      - DB_USER=db2inst1
      - DB_PASS=passw0rd
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080/api
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db2_data:
    driver: local


