services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    environment:
      - SPRING_PROFILES_ACTIVE=h2
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
