-- Initial database schema migration
-- This migration creates the base tables for the photo gallery application

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    profile_picture_filename VARCHAR(255),
    profile_picture_content_type VARCHAR(100),
    profile_picture_size BIGINT,
    profile_picture_data BLOB
);

-- Galleries table
CREATE TABLE galleries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Photos table
CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    original_filename VARCHAR(255),
    content_type VARCHAR(100),
    size BIGINT,
    data BLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    user_id BIGINT NOT NULL,
    gallery_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (gallery_id) REFERENCES galleries(id)
);

-- Create indexes for better performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_photos_user_id ON photos(user_id);
CREATE INDEX idx_photos_gallery_id ON photos(gallery_id);
CREATE INDEX idx_photos_created_at ON photos(created_at);
CREATE INDEX idx_galleries_user_id ON galleries(user_id);
