-- Migration: V1__Initial_Schema
-- Description: Create initial database schema for Photo Gallery application
-- This migration creates all required tables with proper structure

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    profile_picture_filename VARCHAR(255),
    profile_picture_content_type VARCHAR(100),
    profile_picture_size BIGINT,
    profile_picture_data BLOB(1M),
    created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
);

-- Galleries table
CREATE TABLE galleries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Photos table
CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size BIGINT NOT NULL,
    data BLOB(100M) NOT NULL,
    user_id BIGINT NOT NULL,
    gallery_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (gallery_id) REFERENCES galleries(id) ON DELETE SET NULL
);

-- Create indexes for better performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_galleries_user_id ON galleries(user_id);
CREATE INDEX idx_photos_user_id ON photos(user_id);
CREATE INDEX idx_photos_gallery_id ON photos(gallery_id);
CREATE INDEX idx_photos_created_at ON photos(created_at);

-- Insert initial admin user if needed (optional)
-- INSERT INTO users (username, email, password, created_at, updated_at) 
-- VALUES ('admin', 'admin@example.com', '$2a$10$...', CURRENT TIMESTAMP, CURRENT TIMESTAMP);
